CREATE TABLE `yb`.`djzqbm` (
  `DJQMC` VARCHAR(15) NULL,
  `DJZQMC` VARCHAR(15) NOT NULL,
  `DJZQDM` VARCHAR(45) NOT NULL,
  `JDJH` VARCHAR(45) NULL,
  PRIMARY KEY (`DJZQDM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;